---
driver:
  name: docker
platforms:
  - name: instance
    image: centos/systemd:latest
    privileged: True
    port_bindings:
      - 80:80
      - 443:443
    published_ports:
      - 0.0.0.0:80:80/TCP
      - 0.0.0.0:443:443/TCP
    command: "/usr/sbin/init"
lint:
  name: yamllint
provisioner:
  name: ansible
  playbooks:
    converge: ../common/playbook.yml
    prepare: ../common/prepare.yml
  lint:
    name: ansible-lint
scenario:
  name: docker
verifier:
  name: testinfra
  directory: ../tests
  options:
    sudo: true
  lint:
    name: flake8
