---
driver:
  name: docker
platforms:
  - name: instance
    image: centos/systemd:latest
    privileged: True
    port_bindings:
      - 8080:8080
    published_ports:
      - 0.0.0.0:8080:8080/TCP
    command: "/usr/sbin/init"
lint:
  name: yamllint
provisioner:
  name: ansible
  playbooks:
    converge: ../common/playbook.yml
    prepare: ../common/prepare.yml
  lint:
    name: ansible-lint
scenario:
  name: docker
  test_sequence:
    - lint
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  directory: ../tests
  options:
    sudo: true
  lint:
    name: flake8
