---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Ensure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - libselinux-python
