---
# TEST.0001
# This is just a basic example


- hosts: all
  name: TEST.0001
  vars_files:
    - vars.yml

  tasks:

    - name: Standardized initial state
      import_tasks: includes/clean_initial_state.yml

    - name: Perform simple connectivity test
      ping:
